/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "NVIC_interface.h"

int main(void)
{
	NVIC_EnableIRQ(53);
	NVIC_DisableIRQ(53);
	NVIC_SetPendingIRQ(51);
	uint8_t state=NVIC_GetPendingIRQ(51);
    /* Loop forever */
	for(;;);
}
